### PR TITLE
Enable Travis for any branches

### PR DESCRIPTION
**Pull request by tucksaun**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @tucksaun.

**Comment by lyrixx** [comment]
I did that in the past because when you push to this repo and open a PR it will trigger two builds and consumes two Travis slots under the github organization. More over it consumes more energy with any gain 🐧

**Comment by nicolas-grekas** [comment]
I disabled branches on Travis, so we can re-enable without any commit.

**Comment by tucksaun** [comment]
@lyrixx yes I agree but back then we didn't have any release branches and were only targeting master (which is the case now). This prevent having the CI running for PR targeting 4.3 for example.

Plus we are not supposed to push our patches on this repo but on a fork 👼

**Pull request merged**
